name: order-service-deployment

on:
    push:
        branches:
            - master
        paths:
            - 'OrderService/**'

jobs:
    deployment:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Build Docker Image
              run: | 
               cd src/OrderService/OrderService.Core
               docker build -t docker.io/gunsmithemoji/baroque:latest .

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_TOKEN}}
            
            - name: Push Docker image
              run: docker push gunsmithemoji/baroque:latest