name: order-service-deployment

on:
    workflow_run:
      workflows: ["order-service-pipeline"]
      types: [completed]

jobs:
    # check_if_merged_in_master:
    #   runs-on: ubuntu-latest
    #   outputs:
    #     valid: ${{ steps.set_cond.outputs.valid }}

    #   steps:
    #     - id: set_cond
    #       run: |
    #         if [[ "${GITHUB_EVENT}" == "push" && "${GITHUB_HEAD_BRANCH}" == "master" ]]; then
    #           echo "valid=true" >> $GITHUB_OUTPUT
    #         else
    #           echo "valid=false" >> $GITHUB_OUTPUT
    #         fi
    #       env:
    #         GITHUB_EVENT: ${{ github.event.workflow_run.event }}
    #         GITHUB_HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}


    deployment:

        # needs: check_if_merged_in_master
        # if: needs.check_if_merged_in_master.outputs.valid == 'true'

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Build Docker Image
              run: | 
               cd src/OrderService/OrderService.Core
               docker build -t docker.io/gunsmithemoji/baroque:latest .

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_TOKEN}}
            
            - name: Push Docker image
              run: docker push gunsmithemoji/baroque:latest