name: order-service-pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/OrderService

    - name: Build
      run: dotnet build src/OrderService --no-restore

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/OrderService

    - name: Build
      run: dotnet build src/OrderService --no-restore --verbosity minimal

    - name: Run xUnit tests
      run: dotnet test src/OrderService --no-build --no-restore --verbosity minimal

  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore src/OrderService

      - name: Run dotnet format
        run: dotnet format --check --folder src/OrderService